### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by szindel** [streamnative/pulsar-io-lakehouse#739]
**Describe the bug**
When attempting to run the pulsar lakehouse sink example(! https://streamnative.io/blog/announcing-delta-lake-sink-connector-apache-pulsar ) locally, an java error occurs:

ERROR org.apache.pulsar.functions.LocalRunner - Encountered error starting localrunner
java.lang.IllegalArgumentException: Could not validate sink config: Cannot construct instance of `org.apache.pulsar.ecosystem.io.lakehouse.SinkConnectorConfig` (no Creators, like default constructor, exist): abstract types either need to be mapped to concrete types, have custom deserializer, or contain additional type information
 at [Source: UNKNOWN; byte offset: #UNKNOWN]
        at org.apache.pulsar.functions.utils.SinkConfigUtils.validateSinkConfig(SinkConfigUtils.java:747) ~[org.apache.pulsar-pulsar-functions-utils-3.0.5.jar:3.0.5]
        at org.apache.pulsar.functions.utils.SinkConfigUtils.validateSinkConfig(SinkConfigUtils.java:731) ~[org.apache.pulsar-pulsar-functions-utils-3.0.5.jar:3.0.5]
        at org.apache.pulsar.functions.utils.SinkConfigUtils.validateAndExtractDetails(SinkConfigUtils.java:561) ~[org.apache.pulsar-pulsar-functions-utils-3.0.5.jar:3.0.5]
        at org.apache.pulsar.functions.LocalRunner.start(LocalRunner.java:423) ~[org.apache.pulsar-pulsar-functions-local-runner-original-3.0.5.jar:3.0.5]
        at org.apache.pulsar.functions.LocalRunner.main(LocalRunner.java:221) ~[org.apache.pulsar-pulsar-functions-local-runner-original-3.0.5.jar:3.0.5]

**To Reproduce**
After init of the pulsar standalone cluster: run the commands in https://streamnative.io/blog/announcing-delta-lake-sink-connector-apache-pulsar

Actual command: 
PULSAR_HOME/bin/pulsar-admin sinks localrun --sink-config-file /tmp/pulsar-functions/connectors/pulsar-delta-lake-sink-config.json

with the settings from the example: with my local cluster settings updated over where needed (tenant / namespace)

**Expected behavior**
To have the sink create succesfully

**Screenshots**
![image](https://github.com/user-attachments/assets/cf0f30c7-fd24-4352-86e8-70b26520127c)

**Environment**
 - OS: [e.g. Ubuntu]
 - Pulsar version: [e.g. 3.0.5
 - Deployment: standalone
 - Connector pulsar-io-lakehouse-3.0.5.8.nar

**Comment by MTI-GMays** [comment]
For anyone else running into this issue. Use "create" instead of "localrun" to create the sink. This worked for me to run locally
 
cmd:
PULSAR_HOME/bin/pulsar-admin sinks create --sink-config-file /tmp/pulsar-functions/connectors/pulsar-delta-lake-sink-config.json
